routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\PostController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('post', PostController::class);

app/Models/Posts.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use willvincent\Rateable\Rateable;
class Posts extends Model
{
    use HasFactory;
    use Rateable;
    
    protected $fillable = ['title', 'body', 'user_id'];

    public function rating()
{
  return $this->hasMany(Rating::class);
}
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Posts;
use App\Http\Requests\PostRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Illuminate\Contracts\View\View;

class PostController extends Controller
{
    
    public function index(): View
    {
        $posts = Posts::all(); 

        return view('posts.index', compact('posts')); 
    }

    public function create(): View
    {
        return view('posts.create');
    }

    public function store(PostRequest $request): RedirectResponse    
    {
        if (Auth::check()){

            Posts::create([

              'title' => $request->title,
              'body' => $request->body,
              'user_id' => Auth::user()->id

            ]);

        } else {

            return redirect()->route('login')->with('message', 'Please login or register before you can create a post');
        }

        return redirect()->route('post.index')->with('message', 'Post Created Successfully');
    }

    public function show(Posts $post): View
    {
       return view('posts.show', compact('post'));
    }


    public function edit(Posts $post): View | RedirectResponse 
    {
       if(Auth::check() && Auth::id() == $post->user_id){

        return view('posts.edit', compact('post'));

       } else {

        return redirect()->route('login');
       }
    }

   
    public function update(PostRequest $request, Posts $post): RedirectResponse 
    {
        $post->update($request->validated());

        return redirect()->route('post.index')->with('message', 'Post updated Successfully');

    }

    public function destroy(Posts $post): RedirectResponse 
    {
        $post->delete();

        return redirect()->route('post.index')->with('message', 'Post Deleted Successfully');
    }
}

resources/views/home.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
        <div class="col-12 text-center mt-5 pt-5">
                <h5>Welcome to the blog with great articles, click the button below to see them</h5>
            <br>
            <a href="{{ route('post.index') }}" class="btn btn-outline-primary btn-lg mt-5 p-3">{{ __('Show Posts') }}</a>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('sass/app.scss') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('content')

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                    <a href="{{ route('post.index') }}" class="nav-link active text-black " aria-current="page" href="#"> {{ __('Go Back') }}</a>
                    </div>
                    <div class="card-body">

                        @if ($errors->any())
                               <div class="w4/8 m-auto text-center">
                                   @foreach($errors->all() as $error)
                                    <li class="alert alert-danger" role="alert">
                                        {{ $error }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </li>
                                @endforeach
                            </div>
                        @endif

                        <form method="POST" action="{{ route('post.store') }}">
                            @csrf  
                        <div class="mb-3">
                          <input type="text" class="form-control" value="{{ old('name') }}" name="title" id="title" placeholder="Title">
                        </div>
                        <div class="mb-3">
                        <textarea class="form-control"  name="body" placeholder="what is on your mind ?" id="body" rows="5" autofocus ></textarea>
                        </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-outline-secondary btn">
                                        {{ __('Create Post') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 pt-2">
                <a href="{{ route('post.index') }}" class="btn btn-outline-primary btn-sm">{{ __('Go Back') }}</a>
                <div class="border rounded mt-5 pl-4 pr-4 pt-4 pb-4">
                    <h5 class="m-2">Edit Post</h5>
                    <hr>

                    @if ($errors->any())
                               <div class="w4/8 m-auto text-center">
                                   @foreach($errors->all() as $error)
                                    <li class="alert alert-danger" role="alert">
                                        {{ $error }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </li>
                                @endforeach
                            </div>
                        @endif
                    <form  method="POST" action="{{ route('post.update', $post->id) }}">
                        @csrf
                        @method('PUT')

                        <div class="row">
                            <div class="control-group col-12">
                                <input type="text" id="title" class="form-control" name="title"
                                placeholder="Enter Post Title" value="{{ $post->title }}" required>
                            </div>

                            <div class="control-group col-12 mt-2">
                                <textarea id="body" class="form-control" name="body" placeholder="Enter Post Body"
                                rows="5" required>{{ $post->body }}</textarea>
                            </div>
                        </div>
                   
                        <div class="row mt-2">
                            <div class="control-group col-12 text-center">
                                <button id="btn-submit" class="btn btn-outline-primary btn-sm">
                                {{ __('Update Post') }}
                                </button>
                            </div>
                        </div>
                    
                    </form>
                </div>

            </div>
        </div>
    </div>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">

            <div>
                @if (session()->has('message'))
                    <div class="alert alert-success alert-dismissible fade show" >
                        {{ session('message') }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                @endif
            </div>

            <div class="col-12 pt-2">
                 <div class="row">
                    <div class="col-8">
                        <h4 class="display-one mb-3">The Blog!</h4>
                        <h5 class="mb-3">Click on any of the topics to read, edit, delete and to create posts click on the button to your right enjoy !!!</h5>
                    </div>
                    <div class="col-4">
                        <a href="{{ route('post.create') }}" class="btn btn-outline-secondary btn float-right">Create Post</a>
                    </div>
                </div>                
                @forelse($posts as $post)
                    <ul >
                        <li><a class="text-decoration-none" href="{{ route('post.show', $post->id) }}">{{ ucfirst($post->body) }}</a></li>
                    </ul>
                @empty
                    <p class="text-warning">No blog Posts available, kindly create by clicking on the create post button </p>
                @endforelse
            </div>
        </div>
    </div>
<script>
  
@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-12 pt-2">
                  <a href="{{ route('post.index')}}"class="btn btn-outline-secondary btn-sm">{{ __('Go Back') }}</a>
                  <h5 class="display-one mt-3">{{ ucfirst($post->title) }}</h5>
                  <p>{!! $post->body !!}</p> 
                  <hr>
                @if(Auth::check() && Auth::id() == $post->user_id)
                    <div class="d-flex ">
                      <a href="{{ route('post.edit', $post->id) }}" class="btn btn-outline-secondary mt-0 m-3 btn-sm">{{ __('Edit Post') }}</a>
                      <br><br>
                    <form id="delete-frm" method="POST" action="{{ route('post.destroy', $post->id) }}">
                      @method('DELETE')
                      @csrf
                    <button class="btn btn-outline-danger mt-0 m-3 text-color-white btn-sm">{{ __('Delete Post') }}</button>
                  </form>
                   </div>
                @endif
            </div>
        </div>
    </div>
@endsection